apiVersion: v1
entries:
  keycloak-client:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-11-11T10:53:02.137269692Z"
    description: A Helm chart for deploying Keycloak clients with authorization
    digest: ede6943cb09a4c4b7571d6bc98349025da4534603b63403c5ced1ce1d8deeffe
    home: https://github.com/vriesdemichael/keycloak-operator
    keywords:
    - keycloak
    - client
    - oauth2
    - oidc
    - authentication
    kubeVersion: '>=1.27.0'
    maintainers:
    - name: Michael de Vries
    name: keycloak-client
    sources:
    - https://github.com/vriesdemichael/keycloak-operator
    type: application
    urls:
    - https://vriesdemichael.github.io/keycloak-operator/charts/keycloak-client-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-11-11T10:53:02.136673583Z"
    description: A Helm chart for deploying Keycloak clients with authorization
    digest: fb22c39897261c5dba6f599690d68559888f93e7df4b64cec3fc037a2dca8e7a
    home: https://github.com/vriesdemichael/keycloak-operator
    keywords:
    - keycloak
    - client
    - oauth2
    - oidc
    - authentication
    kubeVersion: '>=1.27.0'
    maintainers:
    - name: Michael de Vries
    name: keycloak-client
    sources:
    - https://github.com/vriesdemichael/keycloak-operator
    type: application
    urls:
    - https://vriesdemichael.github.io/keycloak-operator/charts/keycloak-client-0.1.3.tgz
    version: 0.1.3
  keycloak-operator:
  - apiVersion: v2
    appVersion: v0.2.14
    created: "2025-11-11T10:53:02.139685928Z"
    description: A Helm chart for deploying the Keycloak Operator with GitOps compatibility
    digest: bf58a7b81be31a786f07a9bbff6735bc840061321e79121186a82c48d4299e62
    home: https://github.com/vriesdemichael/keycloak-operator
    icon: https://www.keycloak.org/resources/images/icon.svg
    keywords:
    - keycloak
    - operator
    - authentication
    - sso
    - identity
    kubeVersion: '>=1.27.0'
    maintainers:
    - name: Michael de Vries
    name: keycloak-operator
    sources:
    - https://github.com/vriesdemichael/keycloak-operator
    type: application
    urls:
    - https://vriesdemichael.github.io/keycloak-operator/charts/keycloak-operator-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v2
    appVersion: v0.2.14
    created: "2025-11-11T10:53:02.138489903Z"
    description: A Helm chart for deploying the Keycloak Operator with GitOps compatibility
    digest: ea34b465bb9145c16acb8363f67052d38bd78e9582b339a8df687ec194bd1593
    home: https://github.com/vriesdemichael/keycloak-operator
    icon: https://www.keycloak.org/resources/images/icon.svg
    keywords:
    - keycloak
    - operator
    - authentication
    - sso
    - identity
    kubeVersion: '>=1.27.0'
    maintainers:
    - name: Michael de Vries
    name: keycloak-operator
    sources:
    - https://github.com/vriesdemichael/keycloak-operator
    type: application
    urls:
    - https://vriesdemichael.github.io/keycloak-operator/charts/keycloak-operator-0.1.4.tgz
    version: 0.1.4
  keycloak-realm:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-11-11T10:53:02.141504835Z"
    description: A Helm chart for deploying Keycloak realms with authorization
    digest: 898f3741d997135f331f85b1c8ca8a2c14938b402bea712f4d44027513b6cbd7
    home: https://github.com/vriesdemichael/keycloak-operator
    keywords:
    - keycloak
    - realm
    - authentication
    - sso
    - identity
    kubeVersion: '>=1.27.0'
    maintainers:
    - name: Michael de Vries
    name: keycloak-realm
    sources:
    - https://github.com/vriesdemichael/keycloak-operator
    type: application
    urls:
    - https://vriesdemichael.github.io/keycloak-operator/charts/keycloak-realm-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-11-11T10:53:02.140427989Z"
    description: A Helm chart for deploying Keycloak realms with authorization
    digest: cfcb7d03f914d6297375fbb30fddb9d7b4e2db7f905126ac467742eceeadb6ee
    home: https://github.com/vriesdemichael/keycloak-operator
    keywords:
    - keycloak
    - realm
    - authentication
    - sso
    - identity
    kubeVersion: '>=1.27.0'
    maintainers:
    - name: Michael de Vries
    name: keycloak-realm
    sources:
    - https://github.com/vriesdemichael/keycloak-operator
    type: application
    urls:
    - https://vriesdemichael.github.io/keycloak-operator/charts/keycloak-realm-0.1.3.tgz
    version: 0.1.3
generated: "2025-11-11T10:53:02.135939317Z"
