apiVersion: v1
entries:
  keycloak-client:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-11-06T00:33:47.88977315Z"
    description: A Helm chart for deploying Keycloak clients with authorization
    digest: 8ce2d117265d6a2f29515c6dcceec14b7492a1733aed9eb1f815593ca18bc825
    home: https://github.com/vriesdemichael/keycloak-operator
    keywords:
    - keycloak
    - client
    - oauth2
    - oidc
    - authentication
    kubeVersion: '>=1.27.0'
    maintainers:
    - name: Michael de Vries
    name: keycloak-client
    sources:
    - https://github.com/vriesdemichael/keycloak-operator
    type: application
    urls:
    - https://vriesdemichael.github.io/keycloak-operator/charts/keycloak-client-0.1.3.tgz
    version: 0.1.3
  keycloak-operator:
  - apiVersion: v2
    appVersion: v0.2.14
    created: "2025-11-06T00:33:47.891009501Z"
    description: A Helm chart for deploying the Keycloak Operator with GitOps compatibility
    digest: 64cbf508574bf9c4fd934894e2470f816cb293f5e4654ba8411a962a2e819d65
    home: https://github.com/vriesdemichael/keycloak-operator
    icon: https://www.keycloak.org/resources/images/icon.svg
    keywords:
    - keycloak
    - operator
    - authentication
    - sso
    - identity
    kubeVersion: '>=1.27.0'
    maintainers:
    - name: Michael de Vries
    name: keycloak-operator
    sources:
    - https://github.com/vriesdemichael/keycloak-operator
    type: application
    urls:
    - https://vriesdemichael.github.io/keycloak-operator/charts/keycloak-operator-0.1.4.tgz
    version: 0.1.4
  keycloak-realm:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-11-06T00:33:47.891542036Z"
    description: A Helm chart for deploying Keycloak realms with authorization
    digest: 652e0b0253afcf8901ddd2dfa04ee211d0fac89080fae21ac21fc26d8f27e3ea
    home: https://github.com/vriesdemichael/keycloak-operator
    keywords:
    - keycloak
    - realm
    - authentication
    - sso
    - identity
    kubeVersion: '>=1.27.0'
    maintainers:
    - name: Michael de Vries
    name: keycloak-realm
    sources:
    - https://github.com/vriesdemichael/keycloak-operator
    type: application
    urls:
    - https://vriesdemichael.github.io/keycloak-operator/charts/keycloak-realm-0.1.3.tgz
    version: 0.1.3
generated: "2025-11-06T00:33:47.889025964Z"
