apiVersion: v1
entries:
  keycloak-client:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-11-04T23:11:12.299789425Z"
    description: A Helm chart for deploying Keycloak clients with authorization
    digest: 0e6e4211ce5b185b98a75af3d0a0f40fcb8367f8c3dedcb7e5fdede63c953740
    home: https://github.com/vriesdemichael/keycloak-operator
    keywords:
    - keycloak
    - client
    - oauth2
    - oidc
    - authentication
    kubeVersion: '>=1.27.0'
    maintainers:
    - name: Michael de Vries
    name: keycloak-client
    sources:
    - https://github.com/vriesdemichael/keycloak-operator
    type: application
    urls:
    - https://vriesdemichael.github.io/keycloak-operator/charts/keycloak-client-0.1.3.tgz
    version: 0.1.3
  keycloak-operator:
  - apiVersion: v2
    appVersion: v0.2.14
    created: "2025-11-04T23:11:12.301022157Z"
    description: A Helm chart for deploying the Keycloak Operator with GitOps compatibility
    digest: fc0dda78717fa5aa969690ca3993ad4e46630a90332a29ed66f83a7483ce7ab6
    home: https://github.com/vriesdemichael/keycloak-operator
    icon: https://www.keycloak.org/resources/images/icon.svg
    keywords:
    - keycloak
    - operator
    - authentication
    - sso
    - identity
    kubeVersion: '>=1.27.0'
    maintainers:
    - name: Michael de Vries
    name: keycloak-operator
    sources:
    - https://github.com/vriesdemichael/keycloak-operator
    type: application
    urls:
    - https://vriesdemichael.github.io/keycloak-operator/charts/keycloak-operator-0.1.4.tgz
    version: 0.1.4
  keycloak-realm:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-11-04T23:11:12.301560268Z"
    description: A Helm chart for deploying Keycloak realms with authorization
    digest: 74f96cfcf6889d6b71c97a8279a00985017fe1e0a48debfe3f8da2d2bdbfa3d2
    home: https://github.com/vriesdemichael/keycloak-operator
    keywords:
    - keycloak
    - realm
    - authentication
    - sso
    - identity
    kubeVersion: '>=1.27.0'
    maintainers:
    - name: Michael de Vries
    name: keycloak-realm
    sources:
    - https://github.com/vriesdemichael/keycloak-operator
    type: application
    urls:
    - https://vriesdemichael.github.io/keycloak-operator/charts/keycloak-realm-0.1.3.tgz
    version: 0.1.3
generated: "2025-11-04T23:11:12.299049571Z"
