apiVersion: v1
entries:
  keycloak-client:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-11-06T15:40:44.582867515Z"
    description: A Helm chart for deploying Keycloak clients with authorization
    digest: 82663e86ae666f086e1d07fc6488ab9e03f668b1182d8284663b7c2f2d87c487
    home: https://github.com/vriesdemichael/keycloak-operator
    keywords:
    - keycloak
    - client
    - oauth2
    - oidc
    - authentication
    kubeVersion: '>=1.27.0'
    maintainers:
    - name: Michael de Vries
    name: keycloak-client
    sources:
    - https://github.com/vriesdemichael/keycloak-operator
    type: application
    urls:
    - https://vriesdemichael.github.io/keycloak-operator/charts/keycloak-client-0.1.3.tgz
    version: 0.1.3
  keycloak-operator:
  - apiVersion: v2
    appVersion: v0.2.14
    created: "2025-11-06T15:40:44.584096348Z"
    description: A Helm chart for deploying the Keycloak Operator with GitOps compatibility
    digest: 4a038e7a12d6f0093f9d4103e19bb97f9399d068487c4214f9bf3839d970588a
    home: https://github.com/vriesdemichael/keycloak-operator
    icon: https://www.keycloak.org/resources/images/icon.svg
    keywords:
    - keycloak
    - operator
    - authentication
    - sso
    - identity
    kubeVersion: '>=1.27.0'
    maintainers:
    - name: Michael de Vries
    name: keycloak-operator
    sources:
    - https://github.com/vriesdemichael/keycloak-operator
    type: application
    urls:
    - https://vriesdemichael.github.io/keycloak-operator/charts/keycloak-operator-0.1.4.tgz
    version: 0.1.4
  keycloak-realm:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-11-06T15:40:44.584679762Z"
    description: A Helm chart for deploying Keycloak realms with authorization
    digest: 7a83e459e7f386e3f82f591d4d5d74747e4e79a4b33a8bd3ccef5c202fe9e8ca
    home: https://github.com/vriesdemichael/keycloak-operator
    keywords:
    - keycloak
    - realm
    - authentication
    - sso
    - identity
    kubeVersion: '>=1.27.0'
    maintainers:
    - name: Michael de Vries
    name: keycloak-realm
    sources:
    - https://github.com/vriesdemichael/keycloak-operator
    type: application
    urls:
    - https://vriesdemichael.github.io/keycloak-operator/charts/keycloak-realm-0.1.3.tgz
    version: 0.1.3
generated: "2025-11-06T15:40:44.582099416Z"
