apiVersion: v2
name: keycloak-realm
description: A Helm chart for deploying Keycloak realms with authorization
type: application
version: 0.3.9
appVersion: "1.0.0"
keywords:
  - keycloak
  - realm
  - authentication
  - sso
  - identity
home: https://github.com/vriesdemichael/keycloak-operator
sources:
  - https://github.com/vriesdemichael/keycloak-operator
maintainers:
  - name: Michael de Vries
kubeVersion: ">=1.27.0"
