apiVersion: v2
name: keycloak-operator
description: A Helm chart for deploying the Keycloak Operator with GitOps compatibility
type: application
version: 0.4.15
appVersion: "v0.7.11"
keywords:
  - keycloak
  - operator
  - authentication
  - sso
  - identity
home: https://github.com/vriesdemichael/keycloak-operator
sources:
  - https://github.com/vriesdemichael/keycloak-operator
maintainers:
  - name: Michael de Vries
icon: https://www.keycloak.org/resources/images/icon.svg
kubeVersion: ">=1.27.0"
