{{- if .Values.keycloak.enabled }}
{{/* yaml-language-server: $schema=https://vriesdemichael.github.io/keycloak-operator/schemas/v1/Keycloak.json */}}
apiVersion: vriesdemichael.github.io/v1
kind: Keycloak
metadata:
  name: {{ .Values.keycloak.name }}
  namespace: {{ include "keycloak-operator.namespace" . }}
  labels:
    {{- include "keycloak-operator.labels" . | nindent 4 }}
  {{- with include "keycloak-operator.annotations" . }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.keycloak.replicas }}
  image: {{ .Values.keycloak.image }}:{{ .Values.keycloak.version }}

  {{- if .Values.keycloak.database.cnpg.enabled }}
  database:
    type: {{ .Values.keycloak.database.type }}
    host: {{ .Values.keycloak.database.cnpg.clusterName }}-rw
    port: 5432
    database: app
    username: app
    passwordSecret:
      name: {{ .Values.keycloak.database.cnpg.clusterName }}-app
      key: password
  {{- else }}
  database:
    type: {{ .Values.keycloak.database.type }}
    host: {{ .Values.keycloak.database.host }}
    port: {{ .Values.keycloak.database.port }}
    database: {{ .Values.keycloak.database.database }}
    username: {{ .Values.keycloak.database.username }}
    passwordSecret:
      name: {{ .Values.keycloak.database.passwordSecret.name }}
      key: {{ .Values.keycloak.database.passwordSecret.key }}
  {{- end }}

  {{- if .Values.keycloak.ingress.enabled }}
  ingress:
    enabled: true
    {{- with .Values.keycloak.ingress.className }}
    className: {{ . }}
    {{- end }}
    {{- with .Values.keycloak.ingress.annotations }}
    annotations:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.keycloak.ingress.hosts }}
    hosts:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.keycloak.ingress.tls }}
    tls:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}

  {{- with .Values.keycloak.resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
