apiVersion: v2
name: keycloak-client
description: A Helm chart for deploying Keycloak clients with authorization
type: application
version: 0.3.0
appVersion: "1.0.0"
keywords:
  - keycloak
  - client
  - oauth2
  - oidc
  - authentication
home: https://github.com/vriesdemichael/keycloak-operator
sources:
  - https://github.com/vriesdemichael/keycloak-operator
maintainers:
  - name: Michael de Vries
kubeVersion: ">=1.27.0"
